---
title: "Pmmh for alpha"
author: "Andrea Becsek"
date: "05/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rcpp)
library(ggplot2)
library(RcppTN)
```

# Bootstrap Filter in R (Stochastic Volatility)

### Prior Distribution
```{r}
prior_function <- function(n=1, alpha, sigma) rnorm(n, 0.0, sigma / sqrt((1 - alpha^2)))
```

### Transition Function
```{r}
transition_function <- function(x, n=1, alpha, sigma) rnorm(n, mean=alpha*x, sd=sigma)
```

### Emission Function and Likelihood Function
```{r}
emission_function <- function(x, beta) rnorm(n=1, mean=0, sd=beta*exp(x/2))

likelihood_function <- function(y, x, beta) dnorm(x=y, mean=0, sd=beta*exp(x/2))
```

### Data Generation
```{r}
set.seed(192837465)    #123
alpha_true <- 0.91
sigma_true <- 1.0
beta_true  <- 0.5
tmax <- 500
data <- matrix(0, nrow=(tmax+1), ncol=2)
data[1, 1] <- prior_function(n=1, alpha = alpha_true, sigma = sigma_true)
data[1, 2] <- emission_function(data[1, 1], beta = beta_true)
for (i in 2:(tmax+1)){
  data[i, 1] <- transition_function(x=data[i-1, 1], n=1, alpha = alpha_true, sigma = sigma_true)
  data[i, 2] <- emission_function(data[i, 1], beta = beta_true)
}

## x and y without the initial values
y <- data[-1, 2]

plot(1:(tmax+1), data[, 1], type='l', main='Hidden State', xlab='t', ylab='x')
```

### Bootstrap Filter Settings

```{r}
ix = 1:200
sourceCpp("bf_cpp_alpha.cpp")
out <- bf_cpp(data[ix, 2], 300, beta=beta_true, alpha = alpha_true, sigma=sigma_true)
plot(data[ix, 1], type="l")
lines(out$filtered_states, col='red')
```

```{r}
sourceCpp("bf_cpp_alpha.cpp")
N <- 300
out <- pmmh_cpp_bf(thetastart = 0.5, 
                   niter=1000, 
                   N=N, 
                   y=y,
                   burnin=0,
                   alpha = 0.5,
                   beta = beta_true)
out$acceptance
plot(out$samples, type='l')
plot(out$alphasamples, type="l")
```

```{r}
bf_cpp(y = y, N = N, beta = beta_true, alpha = 0.78876, sigma = sigma_true)
```

```{r}
out$acceptance
```

```{r}
plot(out$samples, type='l')
plot(out$alphasamples, type="l")
```

```{r}
n <- length(out$samples) * 0.7
mean(out$samples[-(1:n)])
mean(out$alphasamples[-(1:n)])
mean(out$betasamples[-(1:n)])
```

```{r}
mean(out$samples)
```


