# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Auxiliary Particle Filter
#' 
#' This function is currently limited to the stochastic volatility model.
#' 
#' @param obs A vector of observations to be filtered.
#' @param num_particles A positive integer number of particles to be used
#' in the simulation.
#' @param param A vector of model parameters.
#' 
#' @return A list containing a sample from the empirical distribution; the
#' approximated marginal log-likelihood of the data; the filtered states.
APF <- function(obs, num_particles, param) {
    .Call(`_SMC_APF`, obs, num_particles, param)
}

#' Bootstrap Particle Filter
#' 
#' @param obs A vector of observations to be filtered.
#' @param N The number of particles to be used in the filter.
#' @param param The model parameters to be used within the filter. These are
#' passed in the form c(alpha, beta, sigma).
#' 
#' @return A list containing the filtered states; a sample from the posterior
#' distribution; the log-marginal distribution of the observations.
#' 
BSF <- function(obs, N, param) {
    .Call(`_SMC_BSF`, obs, N, param)
}

