// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// APF_r
Rcpp::List APF_r(arma::colvec obs, int num_particles, arma::vec param);
RcppExport SEXP _SMC_APF_r(SEXP obsSEXP, SEXP num_particlesSEXP, SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< int >::type num_particles(num_particlesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type param(paramSEXP);
    rcpp_result_gen = Rcpp::wrap(APF_r(obs, num_particles, param));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SMC_APF_r", (DL_FUNC) &_SMC_APF_r, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
